#!/bin/sh

# Installazione ubuntu server

#update / upgrade
#
#sudo apt update 
#sudo apt full-upgrade
#sudo reboot
#
## Via snaps
#


sudo systemctl disable --now snapd.socket snapd.service 2>/dev/null
sudo apt purge snapd
sudo apt autoremove --purge

#Poi, per evitare che un futuro apt install te lo reinstalli come dipendenza/raccomandazione, aggiungerei un pin APT:
sudo tee /etc/apt/preferences.d/no-snapd.pref >/dev/null <<'EOF'
Package: snapd
Pin: release *
Pin-Priority: -10
EOF

# Via server specific stuff
sudo touch /etc/cloud/cloud-init.disabled
sudo systemctl mask systemd-networkd-wait-online.service

## Brave
curl -fsS https://dl.brave.com/install.sh | sh

## Pi
curl -fsSL https://pi.dev/install.sh | sh

## Platformio
pipx install platformio

## Firefox
sudo install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

sudo tee /etc/apt/sources.list.d/mozilla.sources > /dev/null << EOF
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Signed-By: /etc/apt/keyrings/packages.mozilla.org.asc
EOF

sudo tee /etc/apt/preferences.d/mozilla > /dev/null << EOF
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
EOF

sudo tee /etc/apt/preferences.d/mozilla > /dev/null << EOF
Package: firefox
Pin: release o=Ubuntu
Pin-Priority: -1
EOF

sudo apt-get update
sudo apt-get install firefox

# Yazi
curl -fsSL https://yazi-rs.github.io/builds/yazi-keyring.gpg | sudo tee /usr/share/keyrings/yazi-keyring.gpg >/dev/null
echo 'deb [signed-by=/usr/share/keyrings/yazi-keyring.gpg] https://yazi-rs.github.io/builds/ stable main' | sudo tee /etc/apt/sources.list.d/yazi.list >/dev/null
sudo apt update && sudo apt install yazi

## Pacchetti
sudo apt install sway kitty mako-notifier libnotify-bin pipewire pipewire-pulse \
wireplumber neovim pass stow build-essential udiskie tree-sitter-cli \
xdg-desktop-portal mesa-utils vainfo intel-media-va-driver-non-free \
restic mpv intel-gpu-tools network-manager keyd \
lazygit unzip hyprland hyprpolkitagent hyprland-qtutils \
hyprpaper mpd ncmpcpp mpc dnscrypt-proxy \
zsh zsh-syntax-highlighting trash-cli \
fontconfig fonts-inter fonts-noto-core fonts-noto-color-emoji \
zathura zathura-pdf-poppler hyprlock hypridle apparmor-utils \
libcanberra-gtk3-module sound-theme-freedesktop rfkill starship \
socat flatpak newsboat pulsemixer tlp thermald btm ripgrep fd-find \
isync msmtp neomutt yazi cups smartmontools nvme-cli fwupd libreoffice \
pipx python3-venv plymouth-themes

# Flatpak
flatpak remote-add --if-not-exists flathub \
  https://flathub.org/repo/flathub.flatpakrepo

# Applicazioni
flatpak install -y flathub \
  md.obsidian.Obsidian \
  org.freecad.FreeCAD \
  org.localsend.localsend_app \
  com.orcaslicer.OrcaSlicer

# Keyd
sudo tee /etc/keyd/default.conf >/dev/null <<'EOF'
[ids]
*

[main]
capslock = overload(control, esc)
EOF

sudo systemctl restart keyd
# systemd
sudo systemctl enable --now NetworkManager

# Git setup
git config --global user.email "glctadori@gmail.com"
git config --global user.name "Gianluca"


# MPD
xdg-user-dirs-update
systemctl --user enable --now mpd.service

# Web filter
sudo web-filter-install

# Zsh shell
chsh -s /bin/zsh

# Font 
setup-nerdfonts

# Disable apparmor  mbsync
sudo aa-disable /etc/apparmor.d/mbsync

# Update xdg mime
update-desktop-database ~/.local/share/applications

# Brightness
sudo usermod -aG video "$USER"

# TLP
sudo systemctl enable --now tlp.service

# Thermald
sudo systemctl enable --now thermald.service

# Soglie batteria BAT1: 75–80%
sudo sed -i \
  '/^[[:space:]#]*START_CHARGE_THRESH_BAT1=/d;
   /^[[:space:]#]*STOP_CHARGE_THRESH_BAT1=/d' \
  /etc/tlp.conf

printf '\nSTART_CHARGE_THRESH_BAT1=75\nSTOP_CHARGE_THRESH_BAT1=80\n' | \
  sudo tee -a /etc/tlp.conf >/dev/null

# Niente autosuspend USB (Arduino, ESP32, seriali ecc.)
sudo sed -i '/^[[:space:]#]*USB_AUTOSUSPEND=/d' /etc/tlp.conf
printf 'USB_AUTOSUSPEND=0\n' | sudo tee -a /etc/tlp.conf >/dev/null

# Applica subito TLP
sudo tlp start

# systemd
systemctl --user daemon-reload

systemctl --user enable --now \
  backup-b2.timer \
  backup-hdd.timer \
  prune-b2.timer \
  prune-hdd.timer \
  mbsync.timer \
  newsboat-refresh.timer \
  projects-auto-push.timer
