[colors]
background=2d353bff
text=d3c6aaff
prompt=9da9a0ff
# placeholder=7a8478ff
input=d3c6aaff
match=a7c080ff
selection=3d484dff
selection-text=d3c6aaff
selection-match=dbbc7fff
counter=859289ff
border=a7c080ff
