[main]
include=~/.config/themes/current/fuzzel.ini
font=JetBrainsMono Nerd Font:size=12
prompt="  "
# placeholder=Cerca applicazioni…
icons-enabled=yes
layer=overlay
width=42
lines=9
line-height=28
horizontal-pad=18
vertical-pad=14
inner-pad=10
image-size-ratio=0.5

[border]
width=2
radius=8
