general {
    ignore_dbus_inhibit = false
}

# 5 min: spegni i monitor
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30 min: suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
