font_family JetBrainsMono Nerd Font
font_size 11
window_padding_width 10 8
remember_window_size no
confirm_os_window_close 0
shell_integration enabled
scrollback_lines 10000
scrollback_pager_history_size 10
scrollback_pager nvim --cmd 'set eventignore=FileType clipboard=unnamedplus' +'nnoremap q ZQ' +'nnoremap <Esc> ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
allow_remote_control yes

background_opacity 0.85

map alt+j scroll_line_down
map alt+k scroll_line_up
map super+y show_scrollback

include ../themes/current/kitty.conf
